### ISSUE TITLE
kitchen-dsc Should Reconnect After a Reboot From the LCM

### ISSUE THREAD

**Issue by PrahlM93** [test-kitchen/kitchen-dsc#13]
As of now, if a resource or configuration that is being tested causes the Local Configuration Manager (LCM) to reboot, kitchen-dsc thinks the converge is complete even though the server is rebooting and may have more configuration to do afterwards. This situation doesn't allow a Test Kitchen user to simply type "kitchen test" to create, converge, verify, and destroy the machine, because the verify will start when the server is rebooting or still applying further configuration.

kitchen-dsc should attempt to reconnect to the server after a reboot from the LCM and wait for the configuration to complete.

**Comment by smurawski** [comment]
yeah, I'm actually working on making this a core thing that test-kitchen understands... so it's coming...

**Comment by PrahlM93** [comment]
@smurawski that's great news. Do you know roughly when it'd be released?
