### ISSUE TITLE
Example on configuration_data option

### ISSUE THREAD

**Issue by PrahlM93** [test-kitchen/kitchen-dsc#15]
Hi Steven,
May you please provide an example of using the configuration_data option in your README.md?

For instance, how would I specify something like this in YAML?
```
$configurationData = @{
    AllNodes = @(
        @{
            NodeName = 'localhost'
            CertificateFile = 'C:\path\to\cert.crt'
        };
    );
}
```

**Comment by smurawski** [comment]
This should get you started - 
https://github.com/smurawski/xWebAdministration/blob/kitchen_test_example/.kitchen.yml#L36
