### ISSUE TITLE
Unable to Apply DSC Configuration on VM

### ISSUE THREAD

**Issue by TraGicCode** [test-kitchen/kitchen-dsc#31]
i'm currently using vagrant + virtualbox.  When trying to run a kitchen test i get the following error.

![image](https://user-images.githubusercontent.com/6224270/30250400-33ab3716-9613-11e7-8dc6-cd6120ef7ada.png)

I literally cloned this repo and have been testing with this.

https://github.com/smurawski/xWebAdministration

**Comment by smurawski** [comment]
@TraGicCode I can't replicate.  It looks like you've got some changed files in the repo (from your posh-git prompt).  Could you share your .kitchen.yml and what files were changed?

**Comment by TraGicCode** [comment]
Resolved.  Was a bug/incompatibility with one of the gems below.  The fix was to ensure they were pinned to the following versions.  I didn't dig in any further to figure out which was the problematic gem


```
gem 'kitchen-dsc', '= 0.10.1'
gem "winrm", "= 2.2.3"
gem "winrm-elevated", "= 1.1.0"
gem "winrm-fs", "= 1.0.1"
gem "test-kitchen", "= 1.16.0"
gem "kitchen-vagrant", "= 1.1.0"
gem 'kitchen-pester', '= 0.8.0'
```

Thanks @smurawski
